apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.schedulerName }}
  labels:
    {{ include "custom-scheduler.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: scheduler
    spec:
    {{- if .Values.scheduler.serviceAccount }}
      serviceAccount: {{ .Values.scheduler.serviceAccount }}
    {{- end }}
      containers:
    {{- if .Values.customScheduler.enabled }}
      - name: {{ .Values.scheduler.schedulerName }}
        image: "{{ .Values.customScheduler.image.repository }}:{{ .Values.customScheduler.image.tag }}"
        imagePullPolicy: {{ .Values.customScheduler.image.pullPolicy }}
        args:
          - -v={{ .Values.customScheduler.klogLevel }}
          - -port=8080
        resources:
{{ toYaml .Values.customScheduler.resources | indent 12 }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
    {{- end }}
      - name: kube-scheduler
        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{ .Values.scheduler.kubeSchedulerImageTag | default (split "-" .Capabilities.KubeVersion.GitVersion)._0 }}
        command:
        - kube-scheduler
        - --port=10261
        - --leader-elect=true
        - --lock-object-name={{ .Values.scheduler.schedulerName }}
        - --lock-object-namespace={{ .Release.Namespace }}
        - --scheduler-name={{ .Values.scheduler.schedulerName }}
        - --v={{ .Values.scheduler.logLevel }}
        - --policy-configmap={{ .Values.scheduler.schedulerName }}-policy
        - --policy-configmap-namespace={{ .Release.Namespace }}
        resources:
{{ toYaml .Values.scheduler.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
    {{- end }}