apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.scheduler.schedulerName }}-policy
  labels:
    {{ include "custom-scheduler.labels" . | indent 4 }}
data:
  policy.cfg: |-
{{ tuple "config/_scheduler-policy-json.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
